### ISSUE TITLE
Aws::CloudFront::UrlSigner#signed_url doesn't work with response-content-disposition and response-content-type parameters

### ISSUE THREAD

**Issue by mwalsher** [aws/aws-sdk-ruby#1391]
If I attempt to sign a URL that contains both `response-content-disposition` and `response-content-type` parameters (per http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html), the resulting signed URL generates an AccessDenied error with the response:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>
```

The headers are:

```
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Thu, 12 Jan 2017 01:42:22 GMT
Content-Type: text/xml
Content-Length: 110
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 2a47832c458ab2a6b20c8363f5aa35ea.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 4uw2hSubT7VYHO0lkShwWW5sN9D3UUEXQzmzdjyZX3bLGKFFU7cHdQ==
```

I am generating my URL (pre-signed) with the following code:

```
def cloudfront_url(style_name: :original, force_download: false, force_content_type: false)
  url = self.content.url(style_name, false)

  if force_download
    url += '?response-content-disposition=' + CGI.escape("attachment;filename=\"#{self.content_file_name}\"")
  end

  if force_content_type
    url += (force_download ? '&' : '?')
    url += 'response-content-type=' + CGI.escape(self.content_content_type)
  end
  url
end
```

Calling e.g. `url = Image.first.cloudfront_url(force_download: true, force_content_type: true)` results in a pre-signed URL that looks like:  `https://my-cname.example.com/images/contents/00b/19a/04-/original/image_1483577021.jpg?response-content-disposition=attachment%3Bfilename%3D%22image.jpg%22&response-content-type=image%2Fjpeg`.

Then, signing that URL with e.g. `cloudfront_signer.signed_url(url, expires: 1.week.from_now)` gives a signed URL that results in the aforementioned AccessDenied error, e.g.:

`https://my-cname.example.com/images/contents/00b/19a/04-/original/image.jpg?response-content-disposition=attachment%3Bfilename%3D%22image.jpg%22&response-content-type=image%2Fjpeg&Expires=1484790420&Signature=X2wUik~TmChxmI7qAm0Fsb4k2kNcBT69MN~c~j0BaPxuwL65kxYKv74MmhxAUGbSG8pyZFeXZ7MR1faz-7gv~AmerT-VA1ePlFD9NlX1P7Fkj6HZGNIhHv4s41dvExJtWrCrbZ66-di74D0b7WZDSnKBx2zi2t~0LlAf0hq8J-28IrfMisAyMa-uVXHKt6ST7YFYBYHW-jw4OuZ9U01BJltgj2pXh7dSgdtO4MceT-CFgG460zcwQhIesmOuit-HS4W7Dug90nppN97Wgmg3t7cCMhj6Gj~VAV8cf96EXh68lXohB4~J8rxUWFsZ2~ABzWrNYBVfqOfIEZzen-aIgQ__&Key-Pair-Id=redacted`

If I include the `response-content-disposition` param, but not the `response-content-type` param, the signed URL works fine.

Perhaps I'm missing something?

**Comment by cjyclaire** [comment]
Taking a look ...

**Comment by cjyclaire** [comment]
@mwalsher Apology for the late reply  and appreciate your patience!

Your code snippets looks good to me, may I ask the gem version used? Recently, there have been a small fix about multiple params #1386, could you try the latest version to see if that works?

**Comment by mwalsher** [comment]
Hi @cjyclaire, thanks for looking into this. The issue appears to have been fixed!

**Comment by FunkyloverOne** [comment]
Guys, I'm not getting it. I simply want to force download, so I'm trying to set Content-Disposition header to "attachment...". Here's a simple test code I'm using to sign URLs via CloudFront (together with `shrine` gem):
```ruby
signer = Aws::CloudFront::UrlSigner.new(
  key_pair_id:      ENV['cloudfront_key_pair_id'],
  private_key_path: Rails.root.join('config', 'cloudfront_pk.pem').to_s
)

s3_options = {
  bucket: ENV['s3_bucket_name'],
  signer: ->(url, **options) do
    p url
    # => "https://dwa4d6760oac.cloudfront.net/store/videomessage/5c474c83b1787743eef9abfe/file/original-e331655862bda2b6a17178bb8ab812e9.webm"
    p options
    # => {:expires=>1579712527}
    p content_disposition = ContentDisposition.attachment('trailer.webm')
    # => "attachment; filename=\"trailer.webm\"; filename*=UTF-8''trailer.webm"
    p final_url =
        "#{url}?response-content-disposition=#{CGI.escape(content_disposition)}"
    # => "https://dwa4d6760oac.cloudfront.net/store/videomessage/5c474c83b1787743eef9abfe/file/original-e331655862bda2b6a17178bb8ab812e9.webm?response-content-disposition=attachment%3B+filename%3D%22trailer.webm%22%3B+filename%2A%3DUTF-8%27%27trailer.webm"
    p signer.signed_url(final_url, **options)
    # => "https://dwa4d6760oac.cloudfront.net/store/videomessage/5c474c83b1787743eef9abfe/file/original-e331655862bda2b6a17178bb8ab812e9.webm?response-content-disposition=attachment%3B+filename%3D%22trailer.webm%22%3B+filename%2A%3DUTF-8%27%27trailer.webm&Expires=1579712527&Signature=Ml2unXhVZkV0RK8z0U1EXZ6zuL9E4Xgr69Xr-JxGdWnkVLm4p0kgLar2RXivquVKz5qGy~Z8CPL~aYNSSaDUDeC~wDOPqzrjHcbROWlHz5uGAqF5f1hrso49tUrq-vvwtbZGpPT0slWvT~WXakaqNIYtbeA4Xm9jFI6MBLLoePGmqPvt55TxXhMrdVnNNq0uW7tpTg7Oh65AKVnnoO4nlnpJGG56fnvm0hvVkfaL7hXiE2kOrdXu2HRllcl1s-hiQG-qm3JASMfLfVwD8WVunOu7bde~zXePjKpIlsFFD9fGjOhqCX-1cQnv4GM0N8oF8yfgvMSfF7mvxcXMGKd0Ug__&Key-Pair-Id=APKAJTJHIO7PFEOVXHRA"
  end
}

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: 'cache', **s3_options),
  store: Shrine::Storage::S3.new(prefix: 'store', **s3_options)
}
```

So my final signed URL in this example is: 
```
https://dwa4d6760oac.cloudfront.net/store/videomessage/5c474c83b1787743eef9abfe/file/original-e331655862bda2b6a17178bb8ab812e9.webm?response-content-disposition=attachment%3B+filename%3D%22trailer.webm%22%3B+filename%2A%3DUTF-8%27%27trailer.webm&Expires=1579712527&Signature=Ml2unXhVZkV0RK8z0U1EXZ6zuL9E4Xgr69Xr-JxGdWnkVLm4p0kgLar2RXivquVKz5qGy~Z8CPL~aYNSSaDUDeC~wDOPqzrjHcbROWlHz5uGAqF5f1hrso49tUrq-vvwtbZGpPT0slWvT~WXakaqNIYtbeA4Xm9jFI6MBLLoePGmqPvt55TxXhMrdVnNNq0uW7tpTg7Oh65AKVnnoO4nlnpJGG56fnvm0hvVkfaL7hXiE2kOrdXu2HRllcl1s-hiQG-qm3JASMfLfVwD8WVunOu7bde~zXePjKpIlsFFD9fGjOhqCX-1cQnv4GM0N8oF8yfgvMSfF7mvxcXMGKd0Ug__&Key-Pair-Id=APKAJTJHIO7PFEOVXHRA
```

But it still does not seem to have proper Content-Disposition headers, you can try it, it should work for year since my comment.
What am I doing wrong? Also why doesn't that `Aws::CloudFront::UrlSigner#signed_url` handle those headers as an input hash like this: 
```ruby
{ response_content_disposition: "my-value-for-this-header-here" }
```

P.S. I guess I'm using the latest CloudFront gem version, like this:
`gem 'aws-sdk-cloudfront', '~> 1.11'`

**Comment by FunkyloverOne** [comment]
@cjyclaire , @diehlaws ping :)

**Comment by igor-alexandrov** [comment]
@FunkyloverOne have you enabled Query String Forwarding and Caching in your distribution behavior settings?

**Comment by FunkyloverOne** [comment]
Hey @igor-alexandrov, thanks for the reply!

I've just enabled Query String Forwarding and Caching, but it doesn't seem to help, also according to the description, it looks like it shouldn't, here:

![sreenshot](https://i.imgur.com/lLcZ8yy.png)

It says S3 don't process query string parameters, and if I understand this functionality correctly - it simply forwards query string to S3 in my case, I guess that's not what I need, right?
What I want to achieve is to make CloudFront add `Content-Disposition` header to response, I think. I could be wrong though :) 

Here's the new link I've signed with that feature enabled, still has no header :(
```
https://dwa4d6760oac.cloudfront.net/store/videomessage/5c595c3a95af9740afb99fdc/file/original-d4315700fb31a7c7e9a9c7d1f92e1c6a.webm?response-content-disposition=attachment%3B+filename%3D%22trailer.webm%22%3B+filename%2A%3DUTF-8%27%27trailer.webm&Expires=1549361998&Signature=V3Z90LVyGgTm8jsncX1RofixOnB5th6LGZ2G81eW8WiiPweW-3fZdrkAkhO-i9PPHpF21jGU6wkRC4EEGbq1ZrNU~3fqyfy2as4C9Mkk7Up-1rCSx4vkUbu4bk1DFXZKIKgOvO66NN7~ssn-lONEabuSsX4aURtMNApUPUPEN4mar6ArIm8wMxbuoZSscP5p24-o84-pCQKZfDwdvk2GWHwCZxi3LB7DLOA~xtDC-xOpwQRMhY3MBKwIfIJ4m5JsQVqXqVhQgsRM7gTUrTiBwuChzjew0pE0LcaZgDvL3yZrFB93Xcdni3Mt~Deo~2sIGiVFAN3z3MlbMQ0kxJhA~A__&Key-Pair-Id=APKAJTJHIO7PFEOVXHRA
```

**Comment by jclusso** [comment]
Why was this closed? I have this same issue and I'm not sure why....

**Comment by jclusso** [comment]
Why was this closed? I have this same issue and I'm not sure why.... @cjyclaire @mwalsher

**Comment by prithvin** [comment]
@jclusso  what was the solution?

**Comment by jclusso** [comment]
@prithvin I manually added the parameter to the URL before I sign it. If you can’t figure it out when I’m on the computer I can send the code I used to do it. I believe I used the URI library to add it IIRC.

**Comment by prithvin** [comment]
thanks @jclusso ,  yep the problem i was having (this is the working code snippet is in javascript for future ref) is that we  **have** to replace URL reserved characters with their UTF-8 encoding

```
signer.getSignedUrl({
  url: `${CLOUDFRONT_DOMAIN}/${keyName}?response-content-disposition=${encodeURIComponent(`inline; filename: test.png;`)}`,
  expires: moment().add(S3_EXPIRY_SECONDS, 'seconds').valueOf(),
})```

**Comment by msedlmairHH** [comment]
Hey @jclusso would you be kind and share your code with me or the rest? I'm stuck with this. I'm getting signature mismatch with signed urls and response-content-disposition

Thank you very much.

**Comment by jclusso** [comment]
@msedlmairHH 

Here is how I'm doing it

```ruby
signer = Aws::CloudFront::UrlSigner.new(
  key_pair_id: Jerky.secret(:cloudfront, :key_pair_id),
  private_key: Jerky.secret(:cloudfront, :private_key)
)

s3_options = {
  bucket: 'bucket',
  region: 'region',
  access_key_id: 'access_key',
  secret_access_key: 'secret_key',
  use_accelerate_endpoint: true,
  signer: -> (base_url, options) do
    options[:expires] ||= 30.minutes.from_now
    uri = URI(base_url)
    content_disposition = options.delete(:'response-content-disposition')
    if content_disposition.present?
      uri.query = {
        'response-content-disposition': content_disposition
      }.to_query
    end

    signer.signed_url(uri.to_s, options)
  end
}```
